language: go

sudo: required

services:
- docker

before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
- make

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: "change-this"
    file:
    - "clipboard-yt-dl_linux"
    - "clipboard-yt-dl_windows.exe"
  skip_cleanup: true
  on:
#    branch: master
    tags: false